version: '3'
services:
    my-redis-server:
        image: redis
        expose:
            - '6379'
        volumes:
            - ./redis-data:/data

    nodebasic-app:
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - '9999:8888'
        depends_on: 
            - my-redis-server
        volumes:
            - ./src:/usr/nodebasicapp/src
        environment:
            SERVERPORT: 8888
